### ISSUE TITLE
Blender dataset

### ISSUE THREAD

**Issue by ZNsea** [YifYang993/CR-NeRF-PyTorch#4]
Can u tell me how to train on blender dataset? i really dont get it. Big thanks for help!!

**Comment by YifYang993** [comment]
Hi, please be more specific, do you mean you don't know how to load the data? or other aspect?

**Comment by ZNsea** [comment]
Thanks for your reply. I actually just need the ruunning commad designed for blender dataset. Like what u did in `train.sh`

**Comment by YifYang993** [comment]
You need to prepare the dataset first, our code support training on blender with a well-prepared blender dataset. I am currently preparing a paper, I will consider trying the blender dataset after submitting this paper.
