### ISSUE TITLE
multiple 2D images to build a 2D image

### ISSUE THREAD

**Issue by Edgar-Lzxc** [YifYang993/CR-NeRF-PyTorch#5]
Realization of multiple 2D images to build a 2D image, fusing the elements of multiple images into a single image, can the project be done?
实现多张二维图片构建一张二维图片，将多张图片的要素融合到一张图片上，该项目能办到吗？

**Comment by YifYang993** [comment]
it depends on the way that you fuse the element of the images, if the elements (appearance, style) are significant in the final image, our CR-NeRF can reconstruct them, see our video demo.




yif&nbsp;young
***@***.***







                       
Original Email
                       
                     

Sender:"Edgar-Lzxc"< ***@***.*** &gt;;

Sent Time:2023/11/20 14:25

To:"YifYang993/CR-NeRF-PyTorch"< ***@***.*** &gt;;

Cc recipient:"Subscribed"< ***@***.*** &gt;;

Subject:[YifYang993/CR-NeRF-PyTorch] multiple 2D images to build a 2D image(Issue #5)




 
Realization of multiple 2D images to build a 2D image, fusing the elements of multiple images into a single image, can the project be done?
 实现多张二维图片构建一张二维图片，将多张图片的要素融合到一张图片上，该项目能办到吗？
