### ISSUE TITLE
How to apply the grid sampling strategy (GS) for eq (9)

### ISSUE THREAD

**Issue by gbliao** [YifYang993/CR-NeRF-PyTorch#6]
Hi, thanks for your interesting work. 

Could you provide more details about the process of eq (9)? Specifically, how to apply the grid sampling strategy (GS) here? 

Thanks a lot.

**Comment by y6216886** [comment]
For the grid-sample strategy, we first uniformly sample the m rays, and the m rays match the m corresponding pixel colors.
(https://github.com/YifYang993/CR-NeRF-PyTorch/blob/bb0828915543dd1230544d933762230808198403/datasets/phototourism_mask_grid_sample.py#L242-L266)

here we get the index of the m pixels 
https://github.com/YifYang993/CR-NeRF-PyTorch/blob/bb0828915543dd1230544d933762230808198403/datasets/phototourism_mask_grid_sample.py#L272

we then use the index to do the same grid sample to the estimated visibility mask on transient objects
https://github.com/YifYang993/CR-NeRF-PyTorch/blob/bb0828915543dd1230544d933762230808198403/train_mask_grid_sample.py#L175
